### PR TITLE
Minor visual changes

### PR DESCRIPTION
**Pull request by macrog**
- single name for a group on mobile phone
- add margin on the right of the patient details
- center version page
- allow downloading pdf on mobile

| now | before |
| --- | --- |
| image | brave_8mk5Mpo7KL |
| image | brave_zZEDgILwNf |
| brave_jncfuzt5aZ | brave_LX2LLIKphl |

### CODE REVIEW

**Comment by macrog** [comment]
squash and merge:

```
refactor: minor visual changes

- single name for a group on mobile phone
- add margin on the right of the patient details
- center version page
```

**Review by Johngtka — APPROVED** [review]
All works good in this pr

**Review by Johngtka — CHANGES_REQUESTED** [review]
Something is doesn't works good
obraz

**Comment by macrog** [comment]
> Something is doesn't works good obraz

For me it works correctly? Just refresh the page and see, maybe it got mixed up changing between mobile and desktop view...
image

If it happens for you just please provide step by step instructions how to reproduce.

**Review by Johngtka — APPROVED** [review]
all works good

**Pull request merged**
