### PR TITLE
New chnges for view of app on monile devices

### PR DESCRIPTION
**Pull request by Johngtka**
| desktop | mobile |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by macrog** [comment]
I have made some changes for mobile @Johngtka 
- show only 2 columns 
- do not show header

Missing:
- add translations for new column, call it "Point"
- make number 1 bigger
- add some space on the sides for number 2
- change text on number 3 to, Patient: {{ mane + surname}} and center and make it smaller the X button on the right
image
image

**Comment by macrog** [comment]
image

change the top part (Patient: name and surname..... button). It should look like this at the end 

| now | what we want |
| --- | --- | 
| ShareX_JAS8IYtGzr | ShareX_ecd0dCeUFw |

**Comment by Johngtka** [comment]
> image
> 
> change the top part (Patient: name and surname..... button). It should look like this at the end 
> 
> | now | what we want |
> | --- | --- | 
> | ShareX_JAS8IYtGzr | ShareX_ecd0dCeUFw |
> 
> 
> 

But when i add margins on the sides of number 2 then  is a problem with close button

**Comment by macrog** [comment]
this is looking better but it's not perfect, first change 20px to 1rem and then add as well padding-right of 1rem if the text is longer to have the same space of padding on both sides

image

**Comment by macrog** [comment]
your centre alignment hurts my eyes 😄 , this will align it horizontally better

image

**Comment by Johngtka** [comment]
> your centre alignment hurts my eyes 😄 , this will align it horizontally better
> 
> image
> 

When I add display: flex then this block wallpaper showed in desktop and mówiłeś before patient select with Patient: undefined undefined text in it @macrog

**Pull request merged**
